<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
<?php include "../Header/Header.php"?>

<div style="">
<br>
<br>
<br>
<br>
    <div class="container" style="width:1500px;">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active" >
            <img src="../Image/foto1.jpg"  alt="Los Angeles" style="width:200%;height:800px;">
          </div>

          <div class="item">
            <img src="../Image/foto2.jpg"  alt="Chicago" style="width:200%;height:800px;">
          </div>
        
          <div class="item">
            <img src="../Image/foto3.jpg"  alt="New york"  style="width:200%;height:800px;">
          </div>
        </div>
        

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div style="color:black;">
      <h3 style="margin-bottom:0px;padding-top:40px;font-size:100px;">Lokasi</h3>
      <h5 style="text-align:justify;margin:0px;padding:40px;font-size:30px;">
      Program Studi Informatika berpusat di gedung 9 lantai 1, bersama-sama dengan program studi lain di bawah Fakultas Teknologi Informasi dan Sains. Kegiatan perkuliahan dilaksanakan di gedung 9 lantai 1 dan gedung 10 lantai 3, sedangkan kegiatan praktikum dilaksanakan di lab komputasi yang berada di gedung 9 lantai semi basement.

      Untuk mengunjungi Program Studi Teknik Informatika, dapat melalui akses pintu depan di Jl. Ciumbuleuit No. 94 maupun akses pintu belakang melalui gedung 10, Jalan Bukitjarian (lebih dekat, dapat ditutup di hari libur). Untuk keduanya, dapat menanyakan kepada petugas lokasi gedung 9.
      </h5>
      </div>
      
    </div>

    
    
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

</div>
</body>
</html>
