<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Penelitian</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Penelitian DTPS yang melibatkan mahasiswa
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Penelitian Melibatkan Mahasiswa.php">Penelitian DTPS yang melibatkan mahasiswa</a>
                    <a href="Penelitian Menjadi Rujukan.php">Penelitian DTPS yang menjadi rujukan tema tesis/disertasi</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>