<html>
    <body>
        <?php include "Penelitian.php"?>
        <div class="">
            <h3>Penelitian DTPS yang melibatkan mahasiswa</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                    <th>jkl</th>

                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Penelitian Melibatkan Mahasiswa.php" target="_blank">Tampilkan Grafik Penelitian DTPS yang melibatkan mahasiswa</a> 
        </div>
    </body>
</html>
