<html>
    <body>
        <?php include "Penelitian.php"?>
        <div class="">
            <h3>Penelitian DTPS yang menjadi rujukan tema tesis/disertasi</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Penelitian Menjadi Rujukan.php" target="_blank">Tampilkan Grafik Penelitian DTPS yang menjadi rujukan tema tesis/disertasi</a> 
        </div>
    </body>
</html>

<script>
    var x = document.getElementById("change2");
    x.innerHTML = "Penelitian DTPS yang menjadi rujukan tema tesis/disertasi";
</script>