<html>
    <body>
        <?php include "Tata Pamong.php"?>
        <div class="">
            <h3>Tabel Detail</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Detail.php" target="_blank">Tampilkan Grafik Detail</a> 
        </div>
    </body>
</html>