<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Tata Pamong, Tata Kelola dan Kerjasama</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Tabel Agregat
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Tabel Agregat.php">Tabel Agregat</a>
                    <a href="Tabel Detail.php">Tabel Detail</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>