<html>
    <body>
        <?php include "Profil Dosen.php"?>
        <div class="">
            <h3>Dosen Pembimbing Utama Tugas Akhir</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Dosen Pembimbing.php" target="_blank">Tampilkan Grafik Dosen Pembimbing Utama Tugas Akhir</a> 
        </div>
    </body>
</html>