<html>
    <body>
        <?php include "Profil Dosen.php"?>
        <div class="">
            <h3>Dosen Industri/Praktisi</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Dosen Industri.php" target="_blank">Tampilkan Grafik Dosen Industri/Praktisi</a> 
        </div>
    </body>
</html>

<script>
    var x = document.getElementById("change");
    x.innerHTML = "Dosen Industri/Praktisi ";
</script>