<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Kinerja Dosen</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn"><span id="change1">Pengakuan/Rekognisi DTPS</span>
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Pengakuan DTPS.php">Pengakuan/Rekognisi DTPS </a>
                    <a href="Penelitian DTPS.php">Penelitian DTPS</a>
                    <a href="PkM DTPS.php">Pengabdian kepada Masyarakat (PkM) DTPS</a>
                    <a href="Pagelaran DTPS.php">Pagelaran/pameran/presentasi/publikasi Ilmiah DTPS</a>
                    <a href="Karya Ilmiah DTPS.php">Karya ilmiah DTPS yang disitasi dalam 3 tahun terakhir</a>
                    <a href="Produk DTPS.php">Produk/jasa DTPS yang diadopsi oleh industri/masyarakat </a>
                    <a href="Luaran Penelitian DTPS.php"> Luaran Penelitian/PkM Lainnya oleh DTPS</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>