<html>
    <body>
        <?php include "Kinerja Dosen.php"?>
        <div class="">
            <h3>Produk/jasa DTPS yang diadopsi oleh industri/masyarakat</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Produk DTPS.php" target="_blank">Tampilkan Grafik Produk/jasa DTPS yang diadopsi oleh industri/masyarakat</a> 
        </div>
    </body>
</html>