<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Profile Dosen</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn"><span id="change">Dosen Tetap Perguruan Tinggi</span>
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Dosen Tetap.php">Dosen Tetap Perguruan Tinggi</a>
                    <a href="Dosen Pembimbing.php" >Dosen Pembimbing Utama Tugas Akhir</a>
                    <a href="EWMP.php"> Ekuivalen Waktu Mengajar Penuh (EWMP) Dosen Tetap Perguruan Tinggi</a>
                    <a href="Dosen Tidak Tetap.php"> Dosen Tidak Tetap Perguruan Tinggi</a>
                </div>

                <div id="content">

                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>
