<!doctype html>
<html>

<head>
    <title>Bar Chart</title>
    <script src="../../Chart.bundle.js"></script>
    <script src="../../utils.js"></script>
    <style>
    canvas{
        -moz-user-select: none;
        -webkit-user-select: none;
        -ms-user-select: none;
    }
    </style>
</head>

<body>
	<div style="width:50%;">
		<canvas id="canvas"></canvas>
	</div>
    <script>
		var dataKeahlian = [5, 1, 2];
		
		var myChart = {
			type: "bar",
			data: {
				datasets : [
					{/* objek 1*/
						label: "Jumlah Dosen",
						data: dataKeahlian,
						borderWidth: 2,
					}],
				labels: ["Informatika", "Fisika Polimer", "Humaniora"],
			},
			options: {
				scales: {
					xAxes: [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: "Bidang Keahlian"
						}
					}],
					yAxes : [{
						display: true,
						scaleLabel: {
							display: true,
							labelString: "Jumlah Dosen"
						}
					}],
				},
				title: {
					display: true,
					text: "Jumlah Dosen Berdasarkan Bidang Keahlian"
				},
				responsive : true
			},
		};
		
		window.onload = function() {
			var ctx = document.getElementById("canvas").getContext("2d");
			new Chart(ctx, myChart);
		};
    </script>
</body>

</html>
