<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Capaian Pembelajaran</h3>
            
            <div class="">
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Capaian Pembelajaran.php" target="_blank">Tampilkan Grafik Capaian Pembelajaran</a> 
        </div>
    </body>
</html>