<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Daya Saing Lulusan</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Waktu Tunggu Lulusan 
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Waktu Tunggu Lulusan.php">Waktu Tunggu Lulusan </a>
                    <a href="Kesesuaian Bidang.php">Kesesuaian Bidang Kerja Lulusan</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>