<html>
    <body>
        <?php include "Luaran Penelitian.php"?>
        <div class="">
            <h3>Karya ilmiah mahasiswa yang disitasi</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Karya Ilmiah.php" target="_blank">Tampilkan Grafik Karya ilmiah mahasiswa yang disitasi</a> 
        </div>
    </body>
</html>