<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Kinerja Lulusan</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Tempat Kerja Lulusan
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Tempat Kerja Lulusan.php">Tempat Kerja Lulusan </a>
                    <a href="Kepuasan Pengguna.php">Kepuasan Pengguna</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>