<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Luaran Penelitan dan PkM Mahasiswa</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Publikasi Ilmiah Mahasiswa
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Publikasi Ilmiah.php">Publikasi Ilmiah Mahasiswa</a>
                    <a href="Pagelaran Ilmiah.php">Pagelaran/pameran/presentasi/publikasi Ilmiah mahasiswa</a>
                    <a href="Karya Ilmiah.php">Karya ilmiah mahasiswa yang disitasi</a>
                    <a href="Produksi Industri.php">Produk/jasa yang dihasilkan mahasiswa yang diadopsi oleh industri/masyarakat</a>
                    <a href="Luaran Mahasiswa.php">Luaran penelitian/PkM yang dihasilkan mahasiswa</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>