<html>
    <body>
        <?php include "Prestasi Mahasiswa.php"?>
        <div class="">
            <h3>Prestasi Akademik</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <div class="">
            <a href="Grafik/Grafik Akademik.php" target="_blank">Tampilkan Grafik Prestasi Akademik</a> 
        </div>
    </body>
</html>