<html>
    <body>
        <?php include "../Header/Header.php"?>

        <div class="">
            <h3>Prestasi Mahasiswa</h3>
            <div class="dropdown dropdownpamong">
                <button class="dropbtn">Prestasi Akademik
                <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-content">
                    <a href="Prestasi Akademik.php">Prestasi Akademik</a>
                    <a href="Prestasi Non Akademik.php">Prestasi Non Akademik</a>
                </div>
            </div> 
        </div>
        <br>
        <br>
        <br>
    </body>
</html>