<html>
    <body>
        <?php include "Luaran Penelitian.php"?>
        <div class="">
            <h3>Publikasi Ilmiah Mahasiswa</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <br>
        <div class="">
            <a href="Grafik/Grafik Publikasi Ilmiah.php" target="_blank">Tampilkan Grafik Publikasi Ilmiah Mahasiswa</a> 
        </div>
    </body>
</html>