<html>
    <body>
        <?php include "Daya Saing Lulusan.php"?>
        <div class="">
            <h3>Waktu Tunggu Lulusan</h3>
            <table>
                <tr>
                    <th>abc</th>
                    <th>def</th>
                    <th>ghi</th>
                </tr>
                <tr>
                <td>Alfreds Futterkiste</td>
                <td>Maria Anders</td>
                <td>Germany</td>
                </tr>
            </table>
        </div>
        <div class="">
            <a href="Grafik/Grafik Waktu Tunggu Lulusan.php" target="_blank">Tampilkan Grafik Waktu Tunggu Lulusan</a> 
        </div>
    </body>
</html>