<html>
    <head>
    <link rel = "stylesheet" href = "../style.css" />
    

<title>Hello, world!</title>
    </head>
    <body>

    <div style="">
                <?php include "../Header/Header.php"?><br>
                <div style="width:50%;margin-left:25%;margin-top:2%;"class=" mx-md-n5">
                <div class="">
            <div class="edit">
             <h3 style="text-align:center;margin-bottom:0px;padding-top:40px;font-size:40px;">Visi</h3><h5 style="margin:0px;padding:40px;font-size:22px;">
                       Visi Program Studi Teknik Informatika UNPAR adalah:<br><br>
                        Menjadi komunitas akademik yang unggul di bidang informatika yang memiliki kemampuan kreatif dan inovatif dan mengembangkan potensi lokal pada tataran internasional demi peningkatan martabat manusia.
                    </h5>
                </div>
            </div>
        </div>
                   
        <div class="">
            <div class="edit"style="width:50%;margin-left:25%;margin-top:2%;"class=" mx-md-n5">
             <h3 style="text-align:center;margin-bottom:0px;padding-top:40px;font-size:40px;">Misi</h3><h5 style="margin:0px;padding:40px;font-size:22px;">
                        Misi Program Studi Teknik Informatika Unpar adalah secara berkesinambungan dan berdasarkan nilai-nilai moral, etika, dan standar akademik yang tinggi melaksanakan:
                        <br>
                        <br>
                        1. Proses pembelajaran di bidang informatika agar menghasilkan lulusan dengan kompetensi akademik yang tinggi, memiliki kemampuan kreatif dan inovatif, softskill serta etika profesional yang menonjol.
                        <br>
                        <br>
                        2. Penelitian di bidang informatika untuk mendukung proses pembelajaran yang bermutu tinggi serta berkontribusi pada pengembangan ilmu bagi masyarakat nasional dan internasional dengan berupaya menggali potensi lokal.
                        <br>
                        <br>
                        3. Pengabdian kepada masyarakat dengan berkontribusi untuk memajukan masyarakat dalam meningkatkan pengetahuan dan pemanfaatan teknologi informasi.
                    </h5>
                </div>
            </div>
        </div>

</div>
       
    </body>
</html>


