<html>
    <body>
        <?php include "../Header/Header.php"?>
        <div class="visimisi">
            <h3>Visi</h3>
            <h5>
                Visi Program Studi Teknik Informatika UNPAR adalah:<br>
                Menjadi komunitas akademik yang unggul di bidang informatika yang memiliki kemampuan kreatif dan inovatif dan mengembangkan potensi lokal pada tataran internasional demi peningkatan martabat manusia.
            </h5>
            <br>
            <h3>Misi</h3>
            <h5>
                Misi Program Studi Teknik Informatika Unpar adalah secara berkesinambungan dan berdasarkan nilai-nilai moral, etika, dan standar akademik yang tinggi melaksanakan:
                <br>
                1. Proses pembelajaran di bidang informatika agar menghasilkan lulusan dengan kompetensi akademik yang tinggi, memiliki kemampuan kreatif dan inovatif, softskill serta etika profesional yang menonjol.
                <br>
                2. Penelitian di bidang informatika untuk mendukung proses pembelajaran yang bermutu tinggi serta berkontribusi pada pengembangan ilmu bagi masyarakat nasional dan internasional dengan berupaya menggali potensi lokal.
                <br>
                3. Pengabdian kepada masyarakat dengan berkontribusi untuk memajukan masyarakat dalam meningkatkan pengetahuan dan pemanfaatan teknologi informasi.
            </h5>
        </div>
    </body>
</html>