<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel = "stylesheet" type = "text/css" href = "../style.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
</head>
<body>
    <div style="text-decoration:none;background-image: url('../Image/kampusCrop.jpg');background-repeat: no-repeat;background-size: cover;" >
        <div style="padding-top:30px;padding-left:20px;padding:50px;">
            <img src="../image/LogoUnpar.png" alt="Trulli" width="100" height="90" >

            <img src="../image/LogoInformatika.jpg" alt="Trulli" width="450" height="80" style="padding-left:30px;" >
            
        </div>    
    </div>
    <h3 style="margin:0px;color:black;text-align:center;font-size:80px;background-color:#1E90FF;">AKREDITASI TEKNIK INFORMATIKA UNPAR</h3>
    
    <div class="navbar" style="background-color:#333333">
        <a href="../Home/Home.php">Home</a>
        <a href="../Visi dan Misi/Visi dan Misi.php">Visi dan Misi</a>
        <a href="../Tata Pamong/Tata Pamong.php">Kerjasama</a>
        <a href="../Mahasiswa/Mahasiswa.php">Mahasiswa</a>
        <div class="dropdown">
            <button class="dropbtn">Sumber Daya Manusia
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Sumber Daya Manusia/Profil Dosen.php">Profil Dosen</a>
                <a href="../Sumber Daya Manusia/Kinerja Dosen.php">Kinerja Dosen</a>
            </div>
        </div> 
        <a href="../Keuangan Sarana Prasarana/Keuangan Sarana Prasarana.php">Keuangan Sarana Prasarana</a>
        <div class="dropdown">
            <button class="dropbtn">Pendidikan
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Pendidikan/Kurikulum.php">Kurikulum</a>
                <a href="../Pendidikan/Integrasi Kegiatan.php">Integrasi Kegiatan Penelitian / PkM Dalam Pembelajaran</a>
            </div>
        </div>
        <a href="../Penelitian/Penelitian.php">Penelitian</a>
        <a href="../Pengabdian Kepada Masyarakat/PkM.php">Pengabdian Kepada Masyarakat</a>
		<a href="../Luaran dan Capaian/Prestasi Mahasiswa.php">Prestasi Mahasiswa</a>
    </div>

</body>
</html>
