<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel = "stylesheet" type = "text/css" href = "../style.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div>
        <img src="../image/LogoUnpar.png" alt="Trulli" width="80" height="80">
        <img src="../image/LogoInformatika.jpg" alt="Trulli" width="300" height="80">
        <h3 style="text-align:center">Akreditasi Teknik Informatika UNPAR</h3>
    </div>
    <div class="navbar">
        <a href="../Home/Home.php">Home</a>
        <a href="../Visi dan Misi/Visi dan Misi.php">Visi dan Misi</a>
        <a href="../Tata Pamong/Tata Pamong.php">Tata Pamong,Tata Kelola dan Kerjasama</a>
        <div class="dropdown">
            <button class="dropbtn">Mahasiswa
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Mahasiswa/Kualitas Input.php">Kualitas Input Mahasiswa</a>
                <a href="../Mahasiswa/Mahasiswa Asing.php">Mahasiswa Asing</a>
            </div>
        </div> 
        <div class="dropdown">
            <button class="dropbtn">Sumber Daya Manusia
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Sumber Daya Manusia/Profil Dosen.php">Profil Dosen</a>
                <a href="../Sumber Daya Manusia/Kinerja Dosen.php">Kinerja Dosen</a>
            </div>
        </div> 
        <a href="../Keuangan Sarana Prasarana/Keuangan Sarana Prasarana.php">Keuangan Sarana Prasarana</a>
        <div class="dropdown">
            <button class="dropbtn">Pendidikan
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Pendidikan/Kurikulum.php">Kurikulum</a>
                <a href="../Pendidikan/Integrasi Kegiatan.php">Integrasi Kegiatan Penelitian / PkM Dalam Pembelajaran</a>
                <a href="../Pendidikan/Kepuasan Mahasiswa.php">Kepuasan Mahasiswa</a>
            </div>
        </div>
        <a href="../Penelitian/Penelitian.php">Penelitian</a>
        <a href="../Pengabdian Kepada Masyarakat/PkM.php">Pengabdian Kepada Masyarakat</a>
        <div class="dropdown">
            <button class="dropbtn">Luaran dan Capaian Tridharma
            <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
                <a href="../Luaran dan Capaian/Capaian Pembelajaran.php">Capaian Pembelajaran</a>
                <a href="../Luaran dan Capaian/Prestasi Mahasiswa.php">Prestasi Mahasiswa</a>
                <a href="../Luaran dan Capaian/Efektivitas Produktivitas.php">Efektivitas dan Produktivitas</a>
                <a href="../Luaran dan Capaian/Daya Saing Lulusan.php">Daya Saing Lulusan</a>
                <a href="../Luaran dan Capaian/Kinerja Lulusan.php">Kinerja Lulusan</a>
                <a href="../Luaran dan Capaian/Luaran Penelitian.php">Lulusan Penelitian dan PkM</a>
            </div>
        </div>
    </div>

</body>
</html>
